name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Atualizar GitHub Stats no README
        uses: anuraghazra/github-readme-stats@v1.0.0

      - name: Commit das mudanças
        run: |
          git config --global user.name "DevBielCastro"
          git config --global user.email "gabriel.castrogt10@gmail.com"
          git add README.md
          git commit -m "Atualizando estatísticas do GitHub no README" || echo "Nenhuma alteração para commit"
          git push
